### ISSUE TITLE
The method 'compareTo' was called on null.

### ISSUE THREAD

**Issue by nyamwaya** [johnpryan/flutter_map#127]
I am using `geocoder` to get the Latitude & Longitude from a supplied address. I do this in the `initState` method. And then I set `stateState` (inside `initState`) to local member variables `double Latitude` and `double Longitude` when I run the app, Null pointer exception `The method compareTo was called on null.` is thrown for a few seconds then it loads the map. I know it's because the `Latitude` & `Longitude` is null when the map is loaded but I can't figure out how to wait until it's not null. I'm guessing the solution is using a `mapController` but I cannot figure out how to implement it correctly. I have my map in a separate class and this is how it looks like. 

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geocoder/geocoder.dart';
import 'package:latlong/latlong.dart';

class MapKwizny extends StatefulWidget {
  MapKwizny({this.address});

  final String address;

  @override
  State<StatefulWidget> createState() => _MapKwiznyState();
}

class _MapKwiznyState extends State<MapKwizny> {
  double lat;
  double long;

  @override
  void initState() {
    super.initState();
    _setLatLong();
  }

  Future _setLatLong() async {
    var addresses = await Geocoder.local.findAddressesFromQuery(widget.address);
    var first = addresses.first;

    setState(() {
      lat = first.coordinates.latitude;
      long = first.coordinates.longitude;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(10.0),

      child: Container(
        padding: const EdgeInsets.all(10.0),
        height: 218.0,
        child: new Card(
          color: Colors.red,
          elevation: 10.0,
          child: new Column(
            children: [
              new Flexible(
                //fit: BoxFit.cover,
                child: new FlutterMap(
                  options: new MapOptions(
                      //minZoom: 10.0,
                      center: new LatLng(lat, long),
                      zoom: 13.0),
                  layers: [
                    TileLayerOptions(
                      urlTemplate: "https://api.tiles.mapbox.com/v4/"
                          "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
                      subdomains: ['a', 'b', 'c'],
                      additionalOptions: {
                        'accessToken':
                            'pk.eyJ1IjoiYWxlY2tzb24iLCJhIjoiY2ptam5lcWFnMGhneTN2cWx1b3UybmVrcyJ9.J6357hZKDUPwyx9Ovz9TQg',
                        'id': 'mapbox.streets',
                      },
                    ),
                    new MarkerLayerOptions(markers: [
                      new Marker(
                          width: 45.0,
                          height: 45.0,
                          point: new LatLng(lat, long),
                          builder: (context) => new Container(
                                child: IconButton(
                                  icon: Icon(Icons.location_on),
                                  color: Colors.red,
                                  onPressed: () {
                                    print('Marker Tapped');
                                  },
                                ),
                              ))
                    ])
                  ],
                ),
              ),
              new FlatButton(
                textColor: Colors.white,
                color: Colors.red,
                onPressed: () => {
                      //TODO: Launch default map app
                    },
                child: new Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Icon(Icons.time_to_leave),
                    Text("Open in Maps",
                        style: TextStyle(
                            fontFamily: 'Quicksand',
                            fontWeight: FontWeight.w800))
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**And then I call it like this, passing in the address**
`MapKwizny(address: widget.address),`

### Here is my crash stacktrace.

```
I/flutter ( 4076): Another exception was thrown: NoSuchMethodError: The method 'compareTo' was called on null.
E/flutter ( 4076): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:E/flutter ( 4076): PlatformException(failed, java.io.IOException: grpc failed, null)
E/flutter ( 4076): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 4076): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 4076): <asynchronous suspension>
E/flutter ( 4076): #2      LocalGeocoding.findAddressesFromQuery (package:geocoder/services/local.dart:18:43)
E/flutter ( 4076): <asynchronous suspension>
E/flutter ( 4076): #3      _MapKwiznyState._setLatLong (package:firebase_auth_world/widgets/map_kwizny.dart:28:42)
E/flutter ( 4076): <asynchronous suspension>
E/flutter ( 4076): #4      _MapKwiznyState.initState (package:firebase_auth_world/widgets/map_kwizny.dart:24:5)
E/flutter ( 4076): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 4076): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4076): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4076): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4076): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
E/flutter ( 4076): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4076): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4076): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 4076): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)E/flutter ( 4076): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 4076): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4076): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4076): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4076): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 4076): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)E/flutter ( 4076): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 4076): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4076): #22     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
E/flutter ( 4076): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4076): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4076): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 4076): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)E/flutter ( 4076): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 4076): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
E/flutter ( 4076): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4076): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4076): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4076): #32     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
E/flutter ( 4076): #33     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:20)
E/flutter ( 4076): #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 4076): #35     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
E/flutter ( 4076): #36     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
E/flutter ( 4076): #37     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
E/flutter ( 4076): #38     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
E/flutter ( 4076): #39     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
E/flutter ( 4076): #40     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)E/flutter ( 4076): #41     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_

```

**Comment by austinrappa78** [comment]
You almost have it working. Just add a swap widget until it is loaded. Like in this video:
https://www.youtube.com/watch?v=x3VvE6WukeY&feature=youtu.be

```
 class _MapKwiznyState extends State<MapKwizny> {
  double lat;
  double long;
  bool loading; //NEW

  @override
  void initState() {
    super.initState();
    _setLatLong();
  }

  Future _setLatLong() async {
    var addresses = await Geocoder.local.findAddressesFromQuery(widget.address);
    var first = addresses.first;

    setState(() {
      lat = first.coordinates.latitude;
      long = first.coordinates.longitude;
      loading = true; //NEW
    });
  }

  @override
  Widget build(BuildContext context) {
    //NEW
    Widget mapWidget;    
    if (loaded)
      mapWidget = _map();
    else
      mapWidget = new Container();  //Maybe a load icon


    return Padding(
      padding: const EdgeInsets.all(10.0),

      child: Container(
        padding: const EdgeInsets.all(10.0),
        height: 218.0,
        child: new Card(
          color: Colors.red,
          elevation: 10.0,
          child: new Column(
            children: [
              new Flexible(
                //fit: BoxFit.cover,
                child: mapWidget	//NEW
                     ),
                  ],
                ),
              ),
              new FlatButton(
              ...
  }



  _map() {
    var markers = <Marker>[
      new Marker(
        width: 80.0,
        height: 80.0,
        point: new LatLng(lat, long),
      )
    ];

    return new FlutterMap(
       ...your map code here...
}
```

Then you need to set a lat and long by telnet into the emulator:
`telnet localhost 5554`
put in your auth token, then:
`geo fix <longitude value> <latitude value>`

**Comment by 5ummit** [comment]
@austinrappa78 mind posting your widget?

**Comment by 5ummit** [comment]
> @austinrappa78 mind posting your widget?

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:shared_preferences/shared_preferences.dart';

class MapView extends StatelessWidget {
  String currenttheme;
  double lat;
  double log;
  MapView({this.lat, this.log, this.currenttheme});


  @override
  Widget build(BuildContext context) {
    if (lat != null && log != null) {
      return new FlutterMap(
      options: new MapOptions(
        center: new LatLng(lat, log),
        zoom: 17.0,
         minZoom: 13.0,
         maxZoom: 18.0,
      ),
      layers: [
        new TileLayerOptions(
          urlTemplate: "https://api.tiles.mapbox.com/v4/"
              "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
          additionalOptions: {
            'accessToken': 'XXXXXXXXXX,
            'id': 'mapbox.streets',
          },
        ),
        new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 80.0,
              height: 80.0,
              point: new LatLng(lat, log),
              builder: (ctx) =>
              new Container(
                child: new FlutterLogo(),
              ),
            ),
          ],
        ),
      ],
    );
    } else {
      return Container(
              color: bg,
              height: 200.0,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget> [
                  Padding(padding: EdgeInsets.all(10.0), child: Icon(Icons.add, size: 22.0)),
                  Text('There was a problem :(', style: TextStyle(color: text, fontSize: 20.0)),
                  Padding(padding: EdgeInsets.all(2.0), child: Text('Looks like there\'s a problem with the event\'s location.', style: TextStyle(color: text)))
                ]
              )
            );
    }
  }
}
```

**Comment by nyamwaya** [comment]
@austinrappa78  this worked for me! I changed you if 'if (loaded)' with 'if (loading)' and I set 'loading = false' at the top just like the video suggested!

Thank you so much for this answer because my app has been on hold the past 4 weeks trying to find an answer. and I had lost hope of someone responding to me! 

@5ummit I am using geocoder too! I get the `lat & long` in `inItState` I'm not sure your question though

**Comment by austinrappa78** [comment]
Hi @5ummit,

Here is my screen widget. Hope this helps.

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:geolocator/geolocator.dart';

///
/// MyAppScreen widget
///
class MyAppScreen extends StatefulWidget {
  MyAppScreen({Key key}) 
    : super(key: key);
  
  
  @override
  _MyAppScreenState createState() => new _MyAppScreenState();
}


///
/// MyAppScreen
///
class _MyAppScreenState extends State<MyAppScreen> {
  List<LatLng> points = [];
  double latitude;
  double longitude;
  bool loaded = false;

  ///
  /// On load
  ///
  @override
  void initState() {    
    super.initState();   
    _getCurrentLocation();
    _getData()     
  }


  ///
  /// Build widget
  /// 
  @override
  Widget build(BuildContext context) {
    //Map widget
    Widget mapWidget;    
    if (loaded)
      mapWidget = _map();
    else
      mapWidget = new Center(
          child: Container(
            color: Colors.grey,
            child: CircularProgressIndicator(),
            alignment: Alignment(0.0, 0.0),
          )                    
    );

    return new Scaffold(
        appBar: new AppBar(title: new Text("My App"), actions: [
          new IconButton(
            icon: new Icon(Icons.refresh),
            onPressed: () {
              _getData();
            }  
          ),
        body: mapWidget);
  }



  ///
  /// Build the map
  /// 
  _map() {
    //The markers
    var markers = points.map((latlng) {
      return new Marker(
        width: 80.0,
        height: 80.0,
        point: latlng,
        builder: (ctx) => new Container(
          child: Image.asset('images/my-marker.png'),
        ),
      );
    }).toList();    

    //The Leaflet.js map
    return new FlutterMap(
      options: new MapOptions(
        center: new LatLng(latitude, longitude),
        zoom: 13.0
      ),      
      layers: [
        new TileLayerOptions(
          //  urlTemplate: "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"),          
          urlTemplate:
            "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            subdomains: ['a', 'b', 'c']),          
        new MarkerLayerOptions(markers: markers)
      ]
    );
  }


  ///
  /// Get the user location
  ///
  Future<bool> _getCurrentLocation() async {
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

    setState(() {
      latitude = position.latitude;
      longitude = position.longitude;
      loaded = true;
    });

    return true;
  }


  ///
  /// Get the nearby posts
  ///
  void _getData() async {
    /*
    In my app I have a RESTAPI call tha returns an array of locations with this schema:
	{
		id: "xxx",	
		name: "xxx",
		latitude: 0.0,
		longitude: 0.0
	}
    Add them to your points variable to show your markers after the map loads.

    myhttpclient.getPoints(latitude, longitude).then((data) {      
      setState(() {
        for (int i = 0; i < data.length; i++) {
          points.add(new LatLng(data[i].latitude, data[i].longitude));
        }
      });
    });
    */
  }
}
```

I hope this helps.

**Comment by comeonbuddy** [comment]
hey @austinrappa78 how can this be done if it is in a stream builder? I got the same issue comparedTo was called on null for a few seconds when loading

`StreamBuilder<QuerySnapshot>(
                stream: Firestore.instance.collection('messages').where('ids', arrayContains: uid).where('blocked', isEqualTo: false).snapshots(),
                builder: (context, msgListSnap) {

                  if (msgListSnap.hasData && msgListSnap.data != null && msgListSnap.data.documents.length != 0) {
                    var messages = msgListSnap.data.documents;

                    if (messages.length > 1){
                      messages.sort((a, b) {
                        return b['lastMsgTime'].compareTo(a['lastMsgTime']);
                      });
                    }

                    return ListView.builder(`

**Comment by johnpryan** [comment]
It looks like @austinrappa78 has answered this. Thanks!
