### ISSUE TITLE
Document how to run the example app

### ISSUE THREAD

**Issue by artob** [johnpryan/flutter_map#216]
I was interested to try the new moving_markers example that you [added](https://github.com/johnpryan/flutter_map/commit/117f1797589bdcceb8d3c49e60c5d0ee262225fa), but it's not immediately clear how to actually run the example app--it looks like some customization of Gradle files might be needed?

A short paragraph about that in the [README](https://github.com/johnpryan/flutter_map/blob/master/example/README.md) would be helpful indeed.

Here's the error I get from `flutter run` in the `example` directory:

    $ flutter run
    Using hardware rendering with device [Device]. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
    Launching lib/main.dart on [Device] in debug mode...
    Initializing gradle...                                       5.0s
    Resolving dependencies...                                        
    * Error running Gradle:
    ProcessException: Process "flutter_map/example/android/gradlew" exited abnormally:

    BUILD FAILED

    Total time: 1.144 secs

    Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
    java.lang.IllegalStateException: buildToolsVersion is not specified.
    	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:558)
    	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
    	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
    	at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
    	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
    	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
    	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
    	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
    	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
    	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
    	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
    	at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:699)
    	at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:691)
    	at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
    	at build_8l642vzw90vl18nwdkr7yzz0a$_run_closure2.doCall(flutter_map/example/android/build.gradle:26)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
    	at groovy.lang.Closure.call(Closure.java:414)
    	at groovy.lang.Closure.call(Closure.java:430)
    	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
    	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
    	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
    	at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:983)
    	at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:988)
    	at org.gradle.api.internal.project.DefaultProject.subprojects(DefaultProject.java:971)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
    	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
    	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
    	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
    	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
    	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)
    	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
    	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    	at build_8l642vzw90vl18nwdkr7yzz0a.run(flutter_map/example/android/build.gradle:24)
    	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
    	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
    	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
    	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
    	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
    	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
    	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
    	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
    	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
    	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
    	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
    	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
    	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
    	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
    	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
    	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
    	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

    FAILURE: Build failed with an exception.

    * Where:
    Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 21

    * What went wrong:
    A problem occurred evaluating script.
    > Could not find method google() for arguments [] on repository container.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
      Command: flutter_map/example/android/gradlew app:properties

    Please review your Gradle project setup in the android/ folder.

This is with Flutter 1.0:

    $ flutter --version
    Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
    Framework • revision 5391447fae (8 weeks ago) • 2018-11-29 19:41:26 -0800
    Engine • revision 7375a0f414
    Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by angel1st** [comment]
+1 from me as well. If updating README is considered as an extra effort and it requires a PR, please give some hints here, so we can proceed with example compilation & run.
> Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (8 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

I am running it under Windows 10 x64 and I can confirm my environment has no problem to compile and run other examples.

**Comment by angel1st** [comment]
@artob - if you are still interested compiling the example app, here is how I did it:
1. Create a new Flutter project
1. Copy both `lib` and `assets` folder from `flutter_map\example\` folder to your new project's folder
1. Update `pubspec.yaml` project file:
    - add `flutter_map: ^0.4.0`
    - add `assets` from `flutter_map\example\pubspec.yaml` file - please note this is required only for offline example
1. Compile and run the app

**Comment by johnpryan** [comment]
The example follows the standard Flutter convention for example apps. After running `pub get` in `example/`, open flutter_map in IntelliJ and navigate to example/lib/main.dart, right-click and click "Run"

@angel1st good catch! be09fc871c47871cec225e237634885c5c881b94 now fixes the moving_markers example

**Comment by artob** [comment]
@johnpryan I would suggest that a standard Flutter app can be run from the command line with `flutter run`, without any need for an IDE. This example app cannot.

It seems likely to be due to `example/android/build.gradle` and `example/android/app/build.gradle` having been created with an older pre-release version of Flutter. It appears this could have broken around Oct 2018 with Flutter 0.8.2 or thereabouts: https://github.com/flutter/flutter/issues/23451

There are many differences between the checked-in files in the example app (hailing from latest Aug 2018) and the equivalent files in a freshly-created Flutter 1.0 project. This is probably why @angel1st's workaround is effective.

**Comment by johnpryan** [comment]
Thanks for the explanation. I'll take a look.

**Comment by johnpryan** [comment]
I think the example is running correctly now.
