### ISSUE TITLE
Error when pinching in Emulator

### ISSUE THREAD

**Issue by MrMoronIV** [johnpryan/flutter_map#278]
To Reproduce: 

1. display the map in a flutter app in the Android Emulator.
2. Hold down Ctrl + move your mouse on the map to go into the two finger gesture mode
3. Keep holding down the Ctrl key at all times during the below steps
4. Move the mouse somewhat to the outside so the gesture gets bigger
5. Move the mouse back to the center where you started the gesture and put the two circles pixel perfect on top of each other.
6. Error gets thrown:

```
E/flutter (23742): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unsupported operation: Infinity or NaN toInt
E/flutter (23742): #0      double.toInt  (dart:core-patch/double.dart:183:36)
E/flutter (23742): #1      double.round  (dart:core-patch/double.dart:151:34)
E/flutter (23742): #2      _TileLayerState._setView
package:flutter_map/…/layer/tile_layer.dart:191
E/flutter (23742): #3      _TileLayerState._resetView
package:flutter_map/…/layer/tile_layer.dart:187
E/flutter (23742): #4      _TileLayerState._handleMove.<anonymous closure>
package:flutter_map/…/layer/tile_layer.dart:163
E/flutter (23742): #5      State.setState 
package:flutter/…/widgets/framework.dart:1117
E/flutter (23742): #6      _TileLayerState._handleMove
package:flutter_map/…/layer/tile_layer.dart:161
E/flutter (23742): #7      _TileLayerState.initState.<anonymous closure>
package:flutter_map/…/layer/tile_layer.dart:152
E/flutter (23742): #8      _rootRunUnary  (dart:async/zone.dart:1132:38)
E/flutter (23742): #9      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (23742): #10     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (23742): #11     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
E/flutter (23742): #12     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
E/flutter (23742): #13     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
E/flutter (23742): #14     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
E/flutter (23742): #15     _rootRun  (dart:async/zone.dart:1120:38)
E/flutter (23742): #16     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (23742): #17     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter (23742): #18     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
E/flutter (23742): #19     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (23742): #20     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (23742): #21     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter (23742): #22     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
E/flutter (23742): #23     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)

```

This is probably never a problem IRL since you can't hold two fingers exactly on top of eachother.

**Comment by johnpryan** [comment]
good catch!
