### ISSUE TITLE
type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'

### ISSUE THREAD

**Issue by synw** [johnpryan/flutter_map#376]
I get a runtime error with version 0.7.0: 

`type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'`

Traceback:

```
I/flutter (19466): The following assertion was thrown building LayoutBuilder:
I/flutter (19466): type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'
I/flutter (19466): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19466): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19466): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19466):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (19466): When the exception was thrown, this was the stack:
I/flutter (19466): #0      PolygonLayer._build 
package:flutter_map/…/layer/polygon_layer.dart:54
I/flutter (19466): #1      PolygonLayer.build.<anonymous closure> 
package:flutter_map/…/layer/polygon_layer.dart:47
I/flutter (19466): #2      _LayoutBuilderElement._layout.<anonymous closure> 
package:flutter/…/widgets/layout_builder.dart:113
I/flutter (19466): #3      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2320
I/flutter (19466): #4      _LayoutBuilderElement._layout 
package:flutter/…/widgets/layout_builder.dart:109
I/flutter (19466): #5      RenderObject.invokeLayoutCallback.<anonymous closure> 
package:flutter/…/rendering/object.dart:1715
I/flutter (19466): #6      PipelineOwner._enableMutationsToDirtySubtrees 
package:flutter/…/rendering/object.dart:796
I/flutter (19466): #7      RenderObject.invokeLayoutCallback 
package:flutter/…/rendering/object.dart:1715
I/flutter (19466): #8      _RenderLayoutBuilder.performLayout
I/flutter (19466): #9      RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #10     RenderStack.performLayout 
package:flutter/…/rendering/stack.dart:510
I/flutter (19466): #11     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #12     RenderConstrainedBox.performLayout 
package:flutter/…/rendering/proxy_box.dart:259
I/flutter (19466): #13     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #15     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #17     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #19     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #21     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #22     _RenderLayoutBuilder.performLayout 
package:flutter/…/widgets/layout_builder.dart:209
I/flutter (19466): #23     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #24     MultiChildLayoutDelegate.layoutChild 
package:flutter/…/rendering/custom_layout.dart:142
I/flutter (19466): #25     _ScaffoldLayout.performLayout 
package:flutter/…/material/scaffold.dart:443
I/flutter (19466): #26     MultiChildLayoutDelegate._callPerformLayout 
package:flutter/…/rendering/custom_layout.dart:212
I/flutter (19466): #27     RenderCustomMultiChildLayoutBox.performLayout
I/flutter (19466): #28     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #30     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #32     _RenderCustomClip.performLayout 
package:flutter/…/rendering/proxy_box.dart:1214
I/flutter (19466): #33     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #35     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #37     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #39     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #41     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #43     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (19466): #45     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
I/flutter (19466): #47     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #48     RenderOffstage.performLayout 
package:flutter/…/rendering/proxy_box.dart:3074
I/flutter (19466): #49     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
I/flutter (19466): #50     RenderStack.performLayout 
package:flutter/…/rendering/stack.dart:510
I/flutter (19466): #51     RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1496
I/flutter (19466): #52     PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:765
I/flutter (19466): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:346
I/flutter (19466): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:701
I/flutter (19466): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:285
I/flutter (19466): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1016
I/flutter (19466): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:958
I/flutter (19466): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:874
I/flutter (19466): #62     _invoke  (dart:ui/hooks.dart:236:10)
I/flutter (19466): #63     _drawFrame  (dart:ui/hooks.dart:194:3)
I/flutter (19466): (elided 3 frames from package dart:async)
I/flutter (19466): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (19466): Another exception was thrown: type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'
```

Flutter doctor output:

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/me/bin/flutter/flutter
    • Framework revision 20e59316b8 (il y a 9 jours), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/me/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/me/Android/Sdk
    • Java binary at: /home/me/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/me/bin/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
```

**Comment by johnpryan** [comment]
There's no clear steps to reproduce, I'm assuming you are using the `stream` somehow? 4956c3b5bc6bd236d0a899611a9ec0c29539a5b6 should fix it and is released in version `0.7.0+1`
