### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by viplike** [johnpryan/flutter_map#409]
**widget code:**
```dart
return Scaffold(
        appBar: AppBar(
          title: Text('Test'),
        ),
        drawer: GuestDrawer(),
        body: Column(children: <Widget>[
              Container(
                alignment: Alignment.centerLeft,
                child: FlutterMap(
                  options: MapOptions(
                    center: LatLng(51.5, -0.09),
                    zoom: 13.0,
                  ),
                  layers: [
                    TileLayerOptions(
                      urlTemplate: "https://api.tiles.mapbox.com/v4/"
                          "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
                      additionalOptions: {
                        'accessToken':
                            '<YOUR_KEY>',
                        'id': 'mapbox.streets',
                      },
                    ),
                    MarkerLayerOptions(
                      markers: [
                        Marker(
                          width: 80.0,
                          height: 80.0,
                          point: LatLng(51.5, -0.09),
                          builder: (ctx) => Container(
                            child: Image.asset(
                                'assets/img/leaflet/marker_blue.png'),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
                padding: EdgeInsets.all(10),
              )
            ]));
  }
```

**error stack:** 
```
I/flutter (16858): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16858): The following UnsupportedError was thrown building LayoutBuilder:
I/flutter (16858): Unsupported operation: Infinity or NaN toInt
I/flutter (16858): When the exception was thrown, this was the stack:
I/flutter (16858): #0      double.toInt (dart:core-patch/double.dart:183:36)
I/flutter (16858): #1      double.round (dart:core-patch/double.dart:151:34)
D/WebView (16858): WebView<init>
I/flutter (16858): #2      CustomPoint.round (package:flutter_map/src/core/point.dart:43:39)
I/flutter (16858): #3      MapState.getNewPixelOrigin (package:flutter_map/src/map/map.dart:269:47)
I/flutter (16858): #4      MapState.move (package:flutter_map/src/map/map.dart:124:20)
I/flutter (16858): #5      MapState._init (package:flutter_map/src/map/map.dart:104:5)
I/flutter (16858): #6      MapState.size= (package:flutter_map/src/map/map.dart:90:7)
I/flutter (16858): #7      FlutterMapState.build.<anonymous closure> (package:flutter_map/src/map/flutter_map_state.dart:92:18)
I/flutter (16858): #8      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
I/flutter (16858): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter (16858): #10     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
I/flutter (16858): #11     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter (16858): #12     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter (16858): #13     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter (16858): #14     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
I/flutter (16858): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #16     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
I/flutter (16858): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (16858): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (16858): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (16858): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #31     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (16858): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #35     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (16858): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #37     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter (16858): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #57     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (16858): #58     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (16858): #59     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (16858): #60     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (16858): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #65     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (16858): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (16858): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #81     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
I/flutter (16858): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (16858): #83     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (16858): #84     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/chromium(16858): [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
I/flutter (16858): #85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (16858): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (16858): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (16858): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (16858): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (16858): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (16858): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (16858): #95     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (16858): #96     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (16858): (elided 3 frames from package dart:async)
```

**Comment by viplike** [comment]
decision is to set height to Container:
```dart
return Scaffold(
        appBar: AppBar(
          title: Text('Test'),
        ),
        drawer: GuestDrawer(),
        body: Column(children: <Widget>[
              Container(
                // here
                height: 100,
                alignment: Alignment.centerLeft,
                child: FlutterMap(
```

**Comment by HerrMuellerluedenscheid** [comment]
> ```dart
>                 alignment: Alignment.centerLeft,
> ```

Doesn't work for me. I can put any height in there and it crashes the same way.

**Comment by ibrierley** [comment]
Have you tried v4 ?

**Comment by HerrMuellerluedenscheid** [comment]
> Have you tried v4 ?

Sorry, my bad. I was using `Row` not `Column` and accordingly had to adjust `width`, not `height`.

**Comment by MohdSaadi** [comment]
i was so confused because the exception thrown was pointing on 

I/flutter (16858): #0      double.toInt (dart:core-patch/double.dart:183:36)
I/flutter (16858): #1      double.round (dart:core-patch/double.dart:151:34)

so first thing came on my thought was there is a problem with my coordinates :D

anyway putting the map widget in a container and specifying its height did the job 👍
