### ISSUE TITLE
Flutter_map ^0.8.2 : Exception: Could not instantiate image codec.

### ISSUE THREAD

**Issue by zgramming** [johnpryan/flutter_map#653]
I have following this [Link](https://www.youtube.com/watch?v=oc1mktx0Zn8) to implement flutter_map . 
I already create **Styles** and **Tilesets**
<img width="960" alt="tanya flutter_map" src="https://user-images.githubusercontent.com/38829404/84593329-e5523c80-ae75-11ea-803d-9c6c1fa73fe7.PNG">
<img width="960" alt="tanya flutter_map2" src="https://user-images.githubusercontent.com/38829404/84593332-e6836980-ae75-11ea-974b-9524bf05feea.PNG">

### Reproduce code

```
class WelcomeScreen extends StatelessWidget {
  static const routeNamed = "/welcome-screen";
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            icon: Icon(Icons.close),
            onPressed: () => _userLogout(context),
          )
        ],
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          FlutterMap(
            options: MapOptions(
              center: LatLng(51.5, -0.09),
              zoom: 13.0,
            ),
            layers: [
              TileLayerOptions(
                urlTemplate:
                    "https://api.mapbox.com/styles/v1/zeffry/ckbf1o8vc2f281ilfl46z986n.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiemVmZnJ5IiwiYSI6ImNrYmV6dnAxMTA3OWgyeGtjMDIybzhrajEifQ.6L2dh0WUdlqCXomQ91WspQ",
                additionalOptions: {
                  'accessToken':
                      'pk.eyJ1IjoiemVmZnJ5IiwiYSI6ImNrYmV6dnAxMTA3OWgyeGtjMDIybzhrajEifQ.6L2dh0WUdlqCXomQ91WspQ',
                  'id': 'mapbox.mapbox-streets-v8'
                },
              ),
              MarkerLayerOptions(
                markers: [
                  Marker(
                    width: 80.0,
                    height: 80.0,
                    point: LatLng(51.5, -0.09),
                    builder: (ctx) => Container(
                      child: FlutterLogo(),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

When i running the app , i get this error  :

```
Exception caught by image resource service
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack
#0      _futurize  (dart:ui/painting.dart:4428:5)
#1      instantiateImageCodec  (dart:ui/painting.dart:1726:10)
#2      PaintingBinding.instantiateImageCodec 
package:flutter/…/painting/binding.dart:88
#3      CachedNetworkImageProvider._loadAsync 
package:cached_network_image/…/image_provider/_image_provider_io.dart:86
<asynchronous suspension>
...
Image provider: CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/zeffry/ckbf1o8vc2f281ilfl46z986n.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiemVmZnJ5IiwiYSI6ImNrYmV6dnAxMTA3OWgyeGtjMDIybzhrajEifQ.6L2dh0WUdlqCXomQ91WspQ", scale: 1.0) 
 Image key: CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/zeffry/ckbf1o8vc2f281ilfl46z986n.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiemVmZnJ5IiwiYSI6ImNrYmV6dnAxMTA3OWgyeGtjMDIybzhrajEifQ.6L2dh0WUdlqCXomQ91WspQ", scale: 1.0): CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/zeffry/ckbf1o8vc2f281ilfl46z986n.html?fresh=true&title=copy&access_token=pk.eyJ1IjoiemVmZnJ5IiwiYSI6ImNrYmV6dnAxMTA3OWgyeGtjMDIybzhrajEifQ.6L2dh0WUdlqCXomQ91WspQ", scale: 1.0)
```

But when i try open **urlTemplate** i can see the map success loaded.
<img width="960" alt="tanya flutter_map3" src="https://user-images.githubusercontent.com/38829404/84593456-9fe23f00-ae76-11ea-82cd-e69738ba3b94.PNG">
I missed Something ?

**Comment by Erik7354** [comment]
You can find the answer (at least for me) in the comments of the YT Video.

"Found the issue, looks like you need to make sure to select CARTO as the type under the Third Party option. This will generate a different URL which is the correct one."

**Comment by zgramming** [comment]
@Erik7354  yes , after select CARTO it's working fine and generate different URL.
